name: CI/CD Frontend

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y Push imagen Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/innovatech-frontend:latest

      - name: Deploy en EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/innovatech-frontend:latest
            docker stop innovatech-frontend || true
            docker rm innovatech-frontend || true
            docker run -d \
              --name innovatech-frontend \
              -p 80:80 \
              --restart unless-stopped \
              ${{ secrets.DOCKERHUB_USERNAME }}/innovatech-frontend:latest